# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
